

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BrokerSolution.Data
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class BrokerCompanyDBEntities : DbContext
{
    public BrokerCompanyDBEntities()
        : base("name=BrokerCompanyDBEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Broker> Broker { get; set; }

    public virtual DbSet<Client> Client { get; set; }

    public virtual DbSet<Contract> Contract { get; set; }

    public virtual DbSet<Deal> Deal { get; set; }

    public virtual DbSet<Role> Role { get; set; }

    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

}

}

