
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BrokerSolution.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Contract
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Contract()
    {

        this.Deal = new HashSet<Deal>();

    }


    public int Number { get; set; }

    public Nullable<int> IdClient { get; set; }

    public Nullable<int> IdBroker { get; set; }



    public virtual Broker Broker { get; set; }

    public virtual Client Client { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Deal> Deal { get; set; }

}

}
